[ashbyhq.com]
page_match = ashbyhq.com
link_match = https://www.ashbyhq.com
destination = ashbyhq.dat

[breezy.hr]
# https://breezy.hr/m/portal?utm_source=Portal&utm_medium=Referral&utm_campaign=Portal
page_match = breezy.hr
link_match = breezy.hr/m/portal?utm_source=Portal
destination = breezy.dat

[crelate.com]
# https://www.crelate.com/recruiting-agency-ats-demo?r=5003&utm_medium=crelate&utm_campaign=poweredbycrelate&utm_source=jobsportalutm_medium=Referral&utm_campaign=Portal
page_match = jobs.crelate.com
link_match = crelate.com/recruiting-agency-ats-demo?r=5003
destination = crelate.dat

[greenhouse.com]
page_match = greenhouse.io
link_match = job-boards.greenhouse.io
destination = greenhouse.dat

[jobscore.com]
# https://www.jobscore.com/applicant_tracking_system?utm_source=maqsoftware&utm_medium=job%20list&utm_campaign=applicant%20tracking%20text&utm_term=careers-site
page_match = jobscore.com
link_match = jobscore.com/applicant_tracking_system?utm_source
destination = jobscore.dat

[jazz.co]
page_match = jazzhr
link_match = info.jazzhr.com/job-seekers.html
destination = jazz.dat

[lever.co]
page_match = lever.co/
link_match = www.lever.co/job-seeker-support/
destination = lever.dat

[pinpointhq.com]
page_match = pinpointhq
link_match = https://www.pinpointhq.com
destination = pinpointhq.dat

[recruitee.com]
page_match = recrutee.com
link_match = https://recruitee.com
destination = recruitee.dat

[smartrecruiters.com]
# https://www.smartrecruiters.com/?utm_source=referral&utm_medium=careerwebsitepage&utm_campaign=careerwebsite&utm_content=none&km_partner=none&km_adgroup=none&utm_term=none&km_ma
page_match = smartrecruiters
link_match = https://www.smartrecruiters.com/?utm_source=referral&utm_medium=careerwebsitepage
destination = smartrecruiters.dat

[teamtailor.com]
page_match = teamtailor.com
link_match = teamtailor.com/?utm_campaign=poweredby
destination = teamtailor.dat

[workable.com]
# https://jobs.workable.com/?utm_campaign=careers_page&utm_content=careers_page&utm_medium=feature&utm_source=careers_page
page_match = workable
link_match = https://jobs.workable.com/?utm_campaign=careers_page&utm_content=careers_page
destination = workable.dat